version: '2'
services:
#  nimbus:
#    command: --daemon nimbus drpc
#    image: docker-registry-cn.easemob.com/im/storm
#    ports:
#      - "3773:3773"
#      - "3772:3772"
#      - "6627:6627"
#    links:
#      - zookeeper:zk
#  supervisor:
#    command: --daemon supervisor logviewer
#    image: docker-registry-cn.easemob.com/im/storm
#    ports:
#      - "8000:8000"
#      - "6700:6700"
#      - "6701:6701"
#      - "6702:6702"
#      - "6703:6703"
#    links:
#      - nimbus:nimbus
#      - zookeeper:zk
#  ui:
#    command: --daemon ui
#    image: docker-registry-cn.easemob.com/im/storm
#    ports:
#      - "8090:8080"
#    links:
#      - nimbus:nimbus
#      - zookeeper:zk
  zookeeper:
    image: docker-registry-cn.easemob.com/zk
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  redis:
    image: docker-registry-cn.easemob.com/redis
    ports:
        - "6379:6379"

  cassandra:
    image: docker-registry-cn.easemob.com/cassandra:2.1.11
    ports:
        - "9160:9160"

  kafka:
    image: docker-registry-cn.easemob.com/im/kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  rest:
    image: docker-registry-cn.easemob.com/im/rest:latest
    ports:
        - "8080:8080"
        - "8081:8081"
    links:
        - cassandra:cassandra
        - zookeeper:zookeeper
        - redis:redis
        - kafka:kafka

  push:
    image: docker-registry-cn.easemob.com/im/tools:latest
    links:
        - cassandra:cassandra
        - zookeeper:zookeeper
        - redis:redis
        - kafka:kafka

  thrift:
    image: docker-registry-cn.easemob.com/im/thrift-login:latest
    ports:
        - "9999:9999"
    links:
        - cassandra:cassandra
        - zookeeper:zookeeper
        - redis:redis

  mysql:
    image: docker-registry-cn.easemob.com/im/mysql
    ports:
        - "3306:3306"

  ejabberd-db:
    image: docker-registry-cn.easemob.com/im/ejabberd:latest
    hostname: ejabberd-db
    ports:
        - "4369:4369"
        - "4370:4370"
    tty: true

  ejabberd-conn:
    image: docker-registry-cn.easemob.com/im/ejabberd:latest
    hostname: ejabberd-conn
    tty: true
    ports:
        - "5222:5222"
        - "5280:5280"
    depends_on:
        - redis
        - mysql
        - kafka
        - thrift
    links:
        - ejabberd-db
        - redis:ejabberd-redis
        - mysql:ejabberd-mysql
        - kafka:ejabberd-kafka
        - thrift:ejabberd-thrift
